{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: "{{ .name }}"
  namespace: kafka
  labels:
    strimzi.io/cluster: {{  $.Values.name }}
spec:
  partitions: {{ .partition }}
  replicas: {{ .replicas | default 1 }}
  config:
    {{ toYaml .config | nindent 4 }}
{{- end}}